CREATE TABLE IF NOT EXISTS public.lemonsqueezy_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id text NOT NULL UNIQUE,
  event_name text,
  email text,
  variant_id text,
  status text,
  raw jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_lemonsqueezy_orders_email
  ON public.lemonsqueezy_orders(email);